FROM node:18-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev
COPY . .

FROM node:18-alpine
WORKDIR /app

COPY --from=builder /app .
ENV NODE_ENV=production
EXPOSE 3002

CMD ["node", "index.js"]